### Lấy danh sách phòng
GET http://localhost:8080/rooms?keyword=phòng%20trọ

### Lấy danh sách phòng có phân trang
GET http://localhost:8080/rooms?page=1&limit=10

### Lọc theo từ khóa
GET http://localhost:8080/rooms?keyword=quận 9

### Lọc theo trạng thái
GET http://localhost:8080/rooms?status=còn trống

### Lọc theo thành phố
GET http://localhost:8080/api/rooms?city=Hồ Chí Minh

### Lọc theo quận
GET http://localhost:8080/rooms?district=Quận 9

### Lọc theo loại phòng
GET http://localhost:8080/api/rooms?city=Hồ

### Lọc theo giá
GET http://localhost:8080/api/rooms?minPrice=2000000&maxPrice=5000000

### Lọc theo chủ trọ
GET http://localhost:8080/rooms?landlordId=1

### Lọc tổng hợp
GET http://localhost:8080/api/rooms?page=1&limit=10

### Lấy chi tiết phòng theo id
GET http://localhost:8080/api/rooms/69d33a2c3f6cc1eeb5d2e9db

### Tạo phòng mới
POST http://localhost:8080/api/rooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZDI2ZTg1MzAxYzI2MDJiZjM3MjIwZCIsInJvbGUiOiJhZG1pbiIsImZ1bGxOYW1lIjoiU2FuZ3VzZXIiLCJpYXQiOjE3NzUzOTg2MDQsImV4cCI6MTc3NTQ4NTAwNH0.7EoWzx-8xwTHUocgx8XJbMqDBzn8VeLGCLFi4c2LOn0

{
  "title": "Phòng trọ cao cấp trung tâm Quận 1 - Đầy đủ tiện nghi",
  "description": "Phòng rộng, thoáng mát, có ban công riêng, giờ giấc tự do, không chung chủ.",
  "price": 5500000,
  "area": 25,
  "address": "123 Lê Lợi, Phường Bến Thành, Quận 1, TP.HCM",
  "city": "Hồ Chí Minh",
  "district": "Quận 1",
  "ward": "Phường Bến Thành",
  "status": "còn trống",
  "type": "Căn hộ mini",
  "electricPrice": 3500,
  "waterPrice": 100000,
  "internetPrice": 150000,
  "maxPeople": 3,
  "furniture": "Máy lạnh, Tủ lạnh, Giường nệm, Tủ quần áo, Máy giặt",
  "latitude": 10.7719,
  "longitude": 106.6991,
  "landlordId": "69d26ccc965e1573eff97449",
  "images": [
    {
      "url": "/uploads/room1.jpg",
      "public_id": "rooms/room1",
      "isThumbnail": true
    }
  ]
}

### Tạo phòng thiếu dữ liệu
POST http://localhost:8080/rooms
Content-Type: application/json

{
  "title": "Phòng test"
}

### Cập nhật phòng
PUT http://localhost:8080/rooms/1
Content-Type: application/json

{
  "title": "Phòng trọ mới sửa, có gác rộng",
  "description": "Phòng đẹp hơn sau khi sửa",
  "price": 4000000,
  "area": 28,
  "address": "123 Lê Văn Việt",
  "city": "Hồ Chí Minh",
  "district": "Quận 9",
  "ward": "Phường Hiệp Phú",
  "latitude": 10.8459231,
  "longitude": 106.7943211,
  "status": "đã thuê",
  "type": "phòng studio",
  "electricPrice": 4000,
  "waterPrice": 18000,
  "internetPrice": 120000,
  "maxPeople": 2,
  "furniture": "máy lạnh, máy giặt, giường, tủ quần áo",
  "landlordId": 1
}

### Xóa phòng
DELETE http://localhost:8080/rooms/1